name: e_commerce
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.9
  cached_network_image: ^3.3.1

  #--------------- ./ PACKAGES END ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/categories/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
