// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv42FuJZMIcvwax-l7mhr20kJ6e1VwfUI',
    appId: '1:781180075185:web:76fd7ae63625edc2887690',
    messagingSenderId: '781180075185',
    projectId: 'airsofteshop-25ad9',
    authDomain: 'airsofteshop-25ad9.firebaseapp.com',
    storageBucket: 'airsofteshop-25ad9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9m74QLTnhTGLstlpC_AQmJ2ozxaF2GL0',
    appId: '1:781180075185:android:98e5b63e759aae03887690',
    messagingSenderId: '781180075185',
    projectId: 'airsofteshop-25ad9',
    storageBucket: 'airsofteshop-25ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAj8qipqIpK-291q-IB9KUVyTpBSHkNjU',
    appId: '1:781180075185:ios:96495b8d424e3ce4887690',
    messagingSenderId: '781180075185',
    projectId: 'airsofteshop-25ad9',
    storageBucket: 'airsofteshop-25ad9.appspot.com',
    androidClientId: '781180075185-778nu2b3skpjqp5lb4inm6ev34g023jv.apps.googleusercontent.com',
    iosClientId: '781180075185-72t41vfeimouicm7gu04h3uinmc0m7gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.strikeshop',
  );

}